#!/bin/bash

echo This is a script that gives instructions on how to update names for this template project.
echo This is a script to remove a small bit of friction from adding stuff that does the updating automatically later.

echo First thing it is probably a good idea to confirm that the template builds and runs properly without any modifications.

list-if-present() {
    local path=$1
    local note=$2
    local needle="rename-me"

    if grep -q "$needle" "$path"; then
        echo "* $path"
        if [ -n "$note" ]; then
            echo "  * $note"
        fi
    fi
}

echo The "rename-me" folder should be renamed to the name of your new project that uses the template.
echo "(We'll keeping referring to that folder with the name \"rename-me\")"
echo 
echo The following files contain references to "rename-me" that should be updated.
list-if-present ./Cargo.toml
list-if-present ./README.md
list-if-present ./rename-me/Cargo.toml 'This also contains authorship information that may need updating.'
list-if-present ./libs/platform/src/platform.rs
list-if-present ./static/index.html
list-if-present ./.project.gf 'This is only needed if you plan to debug with rust-gdb via gf. Otherwise both ./.project.gf and ./rust-gdb can be deleted'
echo

echo "After swapping out \"rename-me\" for your chosen name, building with the updated instuctions should work."

echo 'You might also want to confirm that the license dates are up to date. And if you reading this are not Ryan Wiedemann, you will probably want to update the name(s) on the licenses.'