#!/bin/bash

echo This is a script that gives instructions on how to update names for this template project.
echo This is a script to remove a small bit of friction from adding stuff that does the updating automatically later.

echo Pass "auto" as the first argument and a name as the second argument to try the experimental automatic renaming mode

readonly ORIGINAL_NAME="rename-me"

list-if-present() {
	local path=$1
	local note=$2
	local needle="$ORIGINAL_NAME"

	if grep -q "$needle" "$path"; then
		echo "* $path"
		if [ -n "$note" ]; then
			echo "  * $note"
		fi
	fi
}

case $1 in
  "auto")
	new_name=$2
	if [[ -z "$new_name" ]]; then
		echo
		echo No name argument found. Aborting auto-rename
		exit 1
	fi

	echo renaming to "$new_name"

	replace-in-file() {
		local needle=$1
		local with=$2
		local path=$3

		sed -i "s/$needle/$with/g" "$path"
	}

	replace-in-file "$ORIGINAL_NAME" "$new_name" ./Cargo.toml

	replace-in-file "$ORIGINAL_NAME" "$new_name" ./README.md
	replace-in-file "$ORIGINAL_NAME" "$new_name" ./$ORIGINAL_NAME/Cargo.toml
	mv "$ORIGINAL_NAME/" "$new_name/"
	replace-in-file "$ORIGINAL_NAME" "$new_name" ./libs/platform/src/platform.rs
	replace-in-file "$ORIGINAL_NAME" "$new_name" ./static/index.html
	replace-in-file "$ORIGINAL_NAME" "$new_name" ./.project.gf

	echo "Building with the updated instuctions should now work."

	list-if-present ./"$new_name"/Cargo.toml 'This also contains authorship information that may need updating.'

	;;

  *)
	echo First thing it is probably a good idea to confirm that the template builds and runs properly without any modifications.

	echo The "$ORIGINAL_NAME" folder should be renamed to the name of your new project that uses the template.
	echo "(We'll keeping referring to that folder with the name \"$ORIGINAL_NAME\")"
	echo
	echo The following files contain references to "rename-me" that should be updated.
	list-if-present ./Cargo.toml
	list-if-present ./README.md
	list-if-present ./$ORIGINAL_NAME/Cargo.toml 'This also contains authorship information that may need updating.'
	list-if-present ./libs/platform/src/platform.rs
	list-if-present ./static/index.html
	list-if-present ./.project.gf 'This is only needed if you plan to debug with rust-gdb via gf. Otherwise both ./.project.gf and ./rust-gdb can be deleted'
	echo

	echo "After swapping out \"$ORIGINAL_NAME\" for your chosen name, building with the updated instuctions should work."

	;;
esac

echo 'You might also want to confirm that the license dates are up to date. And if you reading this are not Ryan Wiedemann, you will probably want to update the name(s) on the licenses.'
